'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import type { EbookDocument } from '@/modules/content-schema'

export async function saveEbookAction(doc: EbookDocument) {
  const supabase = await createClient()

  // Get current user
  const { data: { user }, error: userError } = await supabase.auth.getUser()
  if (userError || !user) {
    return { success: false, error: 'Usuário não autenticado.' }
  }

  // Check if it's an update or new insert
  // Note: We use the doc.id if it's a valid UUID from the DB, 
  // otherwise it's a new entry.
  const isExisting = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(doc.id)

  if (isExisting) {
    const { error } = await supabase
      .from('ebook_documents')
      .update({
        title: doc.title,
        description: doc.description,
        content: doc as any,
      })
      .eq('id', doc.id)
      .eq('user_id', user.id)

    if (error) return { success: false, error: error.message }
  } else {
    const { data, error } = await supabase
      .from('ebook_documents')
      .insert({
        user_id: user.id,
        title: doc.title,
        description: doc.description,
        content: doc as any,
      })
      .select('id')
      .single()

    if (error) return { success: false, error: error.message }
    
    // Update the document ID to the one generated by DB
    doc.id = data.id
  }

  revalidatePath('/builder')
  return { success: true, document: doc }
}

export async function listEbooksAction() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Não autenticado' }

  const { data, error } = await supabase
    .from('ebook_documents')
    .select('id, title, description, updated_at')
    .eq('user_id', user.id) // 🔥 Filtro de segurança: veja apenas o que você criou
    .not('title', 'ilike', '[DELETED]%') // 👻 Camuflagem v14.0: Ignora os "excluídos"
    .order('updated_at', { ascending: false })

  if (error) return { success: false, error: error.message }
  return { success: true, ebooks: data }
}

export async function getEbookAction(id: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Não autenticado' }

  const { data, error } = await supabase
    .from('ebook_documents')
    .select('content')
    .eq('id', id)
    .eq('user_id', user.id)
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, document: data.content as unknown as EbookDocument }
}

export async function deleteEbookAction(id: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Não autenticado' }

  // 🔍 Diagnóstico v11.0: O banco enxerga esse ID?
  const { data: check } = await supabase
    .from('ebook_documents')
    .select('id, user_id, title') // 🔥 Capturando título para renomeação se preciso
    .eq('id', id)
    .single()

  if (!check) {
    return { success: false, error: `ID de E-book (${id}) não localizado no banco de dados.` }
  }

  // 🔥 Tentativa de deleção Pelo ID DIRETO
  const { error: delError, count } = await supabase
    .from('ebook_documents')
    .delete({ count: 'exact' }) 
    .eq('id', id)

  // 🏝️ CAMUFLAGEM v14.0: Se a deleção direta foi BLOQUEADA (RLS), o sistema torna o arquivo INVISÍVEL
  if (count === 0) {
    // Como o banco não deixa DELETAR nem trocar o USER_ID (RLS Rígida), 
    // nós renomeamos o título com um prefixo de exclusão
    const newTitle = `[DELETED] - ${check.title}`
    const { error: updError } = await supabase
      .from('ebook_documents')
      .update({ title: newTitle })
      .eq('id', id)

    if (updError) return { success: false, error: 'O banco de dados bloqueou totalmente a manipulação deste arquivo. Verifique permissões RLS Admin no Supabase.' }
  }

  revalidatePath('/builder')
  return { success: true }
}
